begin;
delete from public.menu_items;
insert into public.categories (id,label,icon,position) values
('burgers','Burgers 🍔','🍔',1),
('kids-menu','Kids Menu 👶','👶',2),
('create-my-bun','Crea il tuo Bun 🛠️','🛠️',3),
('piadine','Piadine 🥯','🥯',4),
('wraps','Wraps 🌯','🌯',5),
('hotdogs','Hot Dogs 🌭','🌭',6),
('insalate','Insalate 🥗','🥗',7),
('sfiziosita','Sfiziosità 🍟','🍟',8),
('dolci','Dolci 🍰','🍰',9),
('bevande','Bevande 🍺','🍺',10),
('salse','Salse 🥫','🥫',11)
on conflict (id) do update set label=excluded.label, icon=excluded.icon, position=excluded.position;

insert into public.pills (id,label,color_class,icon) values
('consigliato','Consigliato','pill-recommended','⭐'),
('carne_speziata','Carne Speziata','pill-neutral','🏷️'),
('ispirato_ai_classici','Ispirato ai classici','pill-neutral','🏷️'),
('carico','Carico','pill-heavy','🔥'),
('molto_piccante','Molto Piccante 🌶️🌶️🌶️','pill-spicy','🌶️'),
('novita_mare','Novità Mare','pill-new','🆕'),
('vegetariano','Vegetariano 🌱','pill-veg','🌱'),
('vegano_friendly','Vegano Friendly 🌱','pill-vegan','🌿'),
('per_i_piu_piccoli','Per i più piccoli','pill-neutral','🏷️'),
('tradizione_romagna','Tradizione Romagna','pill-local','📍'),
('super_carico','Super Carico 🔥','pill-heavy','🔥')
on conflict (id) do update set label=excluded.label, color_class=excluded.color_class, icon=excluded.icon;

insert into public.menu_items (name,price,description,image_url,category_id,pill_id,is_popular,is_available,position) values
('LUFFY 👑',11.90,'Hamburger di manzo nostrano, insalata, cipolla caramellata, cheddar, salsa Burger','/menu/luffy.jpg','burgers','consigliato',true,true,1),
('SMOOKYPIG 🐷',12.90,'Pane nero, Pulled Pork speziato, cipolla caramellata, bucciato romagnolo, peperoni arrosto, salsa BBQ, salsa Maionese','/menu/smookypig.jpg','burgers','carne_speziata',true,true,2),
('CHICKENBUN 🐔',10.90,'Cotoletta di pollo, insalata, bacon, bucciato romagnolo, salsa Ketchup, salsa Maionese','/menu/chickenbun.jpg','burgers',null,false,true,3),
('GOTCHESSEBACON',11.90,'Il classico BaconCheese: Hamburger di manzo nostrano, doppio Cheddar, bacon, pomodoro, salsa Burger','/menu/gotcheese-bacon.jpg','burgers','ispirato_ai_classici',false,true,4),
('AMERICANBUN 🇺🇸🍳',12.90,'Hamburger di manzo nostrano, cheddar, uovo all’occhio di bue, bacon, insalata, doppia salsa BBQ','/menu/americanbun.jpg','burgers','carico',false,true,5),
('GUILTY PLEASURE 😋',10.90,'Hamburger di manzo nostrano, cipolla, scamorza affumicata, bacon, salsa Maionese, salsa Ketchup','/menu/guilty-pleasure.jpg','burgers',null,false,true,6),
('HABANERO 🌶️🌶️🌶️',12.90,'Pane nero, hamburger di manzo nostrano, cheddar, bacon, cipolla, cetriolini pickled, salsa Habanero, salsa Maionese','/Menu piatti Got Bun/habanero.webp','burgers','molto_piccante',false,true,7),
('PESCATORE 🐟',12.90,'Salmone affumicato norvegese, squacquerone di Romagna, rucola, pomodorini confit , salsa Avocado','/menu/pescatore.jpg','burgers','novita_mare',false,true,8),
('GREENBUN 🌱',11.90,'Pane ai cereali artigianale, falafel di ceci, bucciato romagnolo, Melanzane grigliate, insalata, salsa Maionese','/menu/greenbun.jpg','burgers','vegetariano',false,true,9),
('LIGHTBUN 🌱',12.90,'Pane Vegano ai 5 Cereali, Falafel di ceci Gotmade, peperoni arrosto, scamorza affumicata, cipolla caramellata, salsa Burger','/menu/lightbun.jpg','burgers','vegano_friendly',false,true,10),
('GOTBABY BURGER',8.40,'Pane Baby artigianale, salsa Ketchup, salsa Maionese, a scelta tra: Hamburger di manzo nostrano, Falafel di ceci GotMade, Cotoletta di pollo, Würstel di pollo e tacchino. Patatine fritte comprese','emoji:👶','kids-menu','per_i_piu_piccoli',false,true,1),
('STORICA 🤫',8.00,'Prosciutto crudo di Parma, squacquerone di Romagna, rucola fresca',null,'piadine','tradizione_romagna',false,true,1),
('MARINARA 🐠',9.00,'Salmone affumicato, Squacquerone di Romagna DOP, rucola fresca',null,'piadine',null,false,true,2),
('PROTEICA 😎',9.00,'Bresaola IGP, scaglie di Grana Padano, rucola fresca',null,'piadine',null,false,true,3),
('PECCATO DI GOLA 😋',8.50,'Salsiccia fresca, cipolla stufata (Aggiunta Squacquerone DOP +0.50€)',null,'piadine',null,true,true,4),
('VEGETALE 🌱',7.50,'Verdure grigliate (melanzane e zucchine), cipolla caramellata, squacquerone di Romagna DOP',null,'piadine','vegetariano',false,true,5),
('SMOOKYPIG WRAP',9.90,'Tortilla Messicana, pulled pork, Cheddar, cipolla , insalata, salsa BBQ','/menu/smookypig-wrap.jpg','wraps',null,false,true,1),
('CHICKEN WRAP',8.90,'Tortilla Messicana, cotoletta di pollo, insalata, pomodoro, patatine fritte, salsa cesar','/menu/chicken-wrap.jpg','wraps',null,false,true,2),
('PROTEIN WRAPP',9.90,'Tortilla Messicana, manzo nostrano, Bucciato romagnolo , insalata, pomodoro, salsa burger','/Menu piatti Got Bun/protein wrap.webp','wraps',null,true,true,3),
('FALAFEL WRAP',8.90,'Tortilla Messicana, falafel di ceci, insalata, pomodoro, cetriolini, Salsa maionese , salsa ketchup','/menu/falafel-wrap.jpg','wraps','vegetariano',false,true,4),
('BASIC HOTDOG',6.90,'Würstel di pollo e tacchino, salsa Ketchup, salsa Maionese','/menu/basic-hotdog.jpg','hotdogs',null,false,true,1),
('GOLOSO DOG',9.90,'Würstel di pollo e tacchino, scamorza affumicata, cipolla caramellata, salsa ketchup, senape','/menu/goloso-dog.jpg','hotdogs',null,true,true,2),
('HOTBACON DOG',8.90,'Würstel di pollo e tacchino, cheddar, bacon, salsa BBQ','/menu/hotbacon-dog.jpg','hotdogs',null,false,true,3),
('VEG DOG 🌱',7.90,'Würstel di falafel, bucciato romagnolo, salsa ketchup , salsa maionese','/menu/veg-dog.jpg','hotdogs','vegetariano',false,true,4),
('Salmone',9.40,'Insalata, salmone affumicato norvegese, pomodorini confit, olive a rondelle rucola, salsa Avocado','/Menu piatti Got Bun/insalata di salmone.webp','insalate',null,false,true,1),
('Imperiale',9.90,'Insalata, Hamburger di manzo nostrano strips, pomodoro, cipolla fresca, scaglie di formaggio, salsa BBQ','/menu/insalata-imperiale.jpg','insalate',null,false,true,2),
('Caesar',9.40,'Insalata, Cotoletta di pollo strips, scaglie di formaggio, crostini di pane, salsa Caesar','/menu/insalata-caesar.jpg','insalate',null,true,true,3),
('Greca',8.90,'Insalata, Feta a cubetti, cetrioli, pomodoro, olive nere a rondelle, cipolla fresca, crema di Aceto Balsamico','/menu/insalata-greca.jpg','insalate','vegetariano',false,true,4),
('Light',8.90,'Insalata, Falafel di ceci strips GotMade, rucola, noci, scaglie di formaggio, crema di aceto balsamico','/menu/insalata-light.jpg','insalate','vegetariano',false,true,5),
('Dirty Fingers',5.90,'Patatine fritte con Pulled Pork speziato, salsa Cheddar, salsa BBQ','/menu/dirty-fingers.jpg','sfiziosita','super_carico',false,true,1),
('Anelli di Cipolla',5.90,'Rondelle di cipolla pastellate e fritte','/menu/anelli-cipolla.jpg','sfiziosita',null,false,true,2),
('Patatine Classic Piccole',1.90,'Patatine fritte ma più croccanti','/menu/patatine-classic-piccole.jpg','sfiziosita',null,false,true,3),
('Patatine fritte Classic Grandi',3.90,'Patatine classiche ma più croccanti','/menu/patatine-classic-grandi.jpg','sfiziosita',null,false,true,4),
('Patatine Crispers Piccola',2.90,'Spicchi di patate croccanti, con la buccia','/menu/patatine-crispers-piccola.jpg','sfiziosita',null,false,true,5),
('Patatine Crispers Grandi',4.50,'Spicchi di patate croccanti, con la buccia','/menu/patatine-crispers-grandi.jpg','sfiziosita',null,false,true,6),
('Olive all’ Ascolana',5.90,'Palline fritte ripiene di carne macinata e oliva','/menu/olive-ascolana.jpg','sfiziosita',null,false,true,7),
('Pepite di Pollo 6 pezzi',5.90,'Pepite di pollo fresco fatte in casa 6 pezzi','/menu/pepite-pollo-6.jpg','sfiziosita',null,false,true,8),
('Pepite di pollo 9 pezzi',7.90,'Pepite di pollo fresco fatte in casa 9 pezzi','/menu/pepite-pollo-9.jpg','sfiziosita',null,false,true,9),
('Petali di Cipolla',5.90,'Fettine di cipolla pastellate e fritte','/menu/petali-cipolla.jpg','sfiziosita',null,false,true,10),
('Mozzarelline in Carrozza 6 Pezzi',5.90,'Deliziosi bocconcini di mozzarella, fritti','/menu/mozzarelline-6.jpg','sfiziosita',null,false,true,11),
('Mozzarelline in carrozza 9 pezzi',7.90,'Deliziosi bocconcini di mozzarella, fritti','/menu/mozzarelline-9.jpg','sfiziosita',null,false,true,12),
('Apple Pie',4.90,'Delizioso trancio di torta di mele','/menu/apple-pie.jpg','dolci',null,false,true,1),
('Brownie',4.90,'Classico dolce americano, “cioccolatoso” e saporito','/menu/brownie.jpg','dolci',null,false,true,2),
('Franziskaner Weissbier 50cl',4.00,'Birra Weiss di alta qualità','/Menu piatti Got Bun/franziskaner 50cl.webp','bevande',null,false,true,1),
('Ichnusa non filtrata 33cl',3.50,'Birra Sarda non filtrata','/Menu piatti Got Bun/ichnusa 33cl.webp','bevande',null,false,true,2),
('Ichnusa non filtrata 50cl',4.50,'Birra Sarda non filtrata','/Menu piatti Got Bun/ichnusa non filtrata 50cl.webp','bevande',null,false,true,3),
('Corona 33cl',4.00,'Messicana chiara rinfrescante','/Menu piatti Got Bun/corona extra.webp','bevande',null,false,true,4),
('Ceres 33cl',4.00,'Strong lager a doppia fermentazione','/Menu piatti Got Bun/ceres.webp','bevande',null,false,true,5),
('Messina 33cl',3.50,'Ricetta classica siciliana con cristalli di sale','/Menu piatti Got Bun/messina 33.webp','bevande',null,false,true,6),
('Birra Moretti filtrata a freddo 33cl',3.50,'Birra lager filtrata a freddo','/Menu piatti Got Bun/moretti filtrata 33.webp','bevande',null,false,true,7),
('Birra Moretti 0.0% Alcol 33cl',3.50,'Zero alcol, gusto pieno','/Menu piatti Got Bun/moretti 0 alcool.webp','bevande',null,false,true,8),
('Birra Amarcord Gradisca 33cl',4.00,'Birra bionda artigianale del territorio','/Menu piatti Got Bun/amarcord.webp','bevande',null,false,true,9),
('San Miguel 1L',6.00,'Formato condivisione da 1 litro','/Menu piatti Got Bun/san miguel 1l.webp','bevande',null,false,true,10),
('Acqua Naturale 50cl',1.50,'Acqua minerale naturale','/Menu piatti Got Bun/acqua naturale.webp','bevande',null,false,true,11),
('Acqua Frizzante 50cl',1.50,'Acqua minerale frizzante','/Menu piatti Got Bun/acqua frizzante 50cl.webp','bevande',null,false,true,12),
('Acqua Naturale 1L',2.50,'Acqua minerale naturale in bottiglia grande','/Menu piatti Got Bun/acqua naturale 1l.webp','bevande',null,false,true,13),
('Acqua Frizzante 1L',2.50,'Acqua minerale frizzante in bottiglia grande','/Menu piatti Got Bun/acqua frizzante 1l.webp','bevande',null,false,true,14),
('Coca Cola 33cl',2.50,'Lattina da 33cl classica','/Menu piatti Got Bun/coca cola.webp','bevande',null,false,true,15),
('Coca Cola Zero 33cl',2.50,'Lattina da 33cl senza zuccheri','/Menu piatti Got Bun/coca cola zero.webp','bevande',null,false,true,16),
('Coca Cola 1.5L',4.50,'Bottiglia grande classica per asporto','/Menu piatti Got Bun/coca cola 1.5l.webp','bevande',null,false,true,17),
('Coca Cola Zero 1.5L',4.50,'Bottiglia grande senza zuccheri per asporto','/Menu piatti Got Bun/coca cola zero 1.5l.webp','bevande',null,false,true,18),
('Fanta 33cl',2.50,'Bibita all''arancia','/Menu piatti Got Bun/fanta.webp','bevande',null,false,true,19),
('Sprite 33cl',2.50,'Bibita limone e lime','/Menu piatti Got Bun/sprite.webp','bevande',null,false,true,20),
('The Limone 33cl',2.50,'Te freddo San Benedetto o Estathé','/Menu piatti Got Bun/te al limone.webp','bevande',null,false,true,21),
('The Pesca 33cl',2.50,'Te freddo San Benedetto o Estathé','/Menu piatti Got Bun/te alla pesca.webp','bevande',null,false,true,22),
('Redbull 25cl',3.00,'Energy drink','/Menu piatti Got Bun/redbull.webp','bevande',null,false,true,23),
('Budweiser 33cl',4.00,'American lager pulita e leggera',null,'bevande',null,false,true,24),
('Salsa Ketchup',0.50,'Fatta in casa con pomodori freschi','/Menu piatti Got Bun/salsa ketchup.webp','salse',null,false,true,1),
('Salsa Maionese (Veg)',0.50,'Fatta in casa, 100% vegetale','/Menu piatti Got Bun/salsa maionese.webp','salse',null,false,true,2),
('Salsa BBQ',0.50,'Fatta in casa, gusto affumicato','/Menu piatti Got Bun/salsa barbecue.webp','salse',null,false,true,3),
('Salsa Habanero',0.80,'Fatta in casa, molto piccante 🌶️🌶️🌶️','/Menu piatti Got Bun/salsa habanero.webp','salse',null,false,true,4),
('Salsa Senape',0.50,'Salsa senape tradizionale','/Menu piatti Got Bun/salsa senape.webp','salse',null,false,true,5),
('Salsa Burger',0.50,'Salsa signature GotBun per panini','/Menu piatti Got Bun/salsa burger.webp','salse',null,false,true,6);

insert into public.promotions (name,key,is_active,settings) values
('Offerta 2x1','promo_2x1',true,'{"description":"Uno lo paghi. L''altro lo morde chi vuoi.","conditions":"La promo si applica esclusivamente sull''acquisto di una portata principale a scelta (Hamburger Nostrani, Piadine, Wrap o Insalate). Sono categoricamente esclusi dalla promozione stuzzichini, appetizer, fritti, dolci e tutte le bevande. Offerta non cumulabile con altri sconti, utilizzabile per una sola consumazione al tavolo."}'::jsonb),
('Sconto Delivery/Asporto -10%','promo_10',true,'{"description":"Gusta dove vuoi. Risparmia online.","conditions":"Sconto del 10% applicabile a fronte di una spesa minima di 20€. Valido esclusivamente per gli ordini effettuati sul nostro portale ufficiale in modalità Delivery (consegna a domicilio) o Asporto (takeaway).","code":"BUN26","minSpend":20}'::jsonb)
on conflict (key) do update set name=excluded.name,is_active=excluded.is_active,settings=excluded.settings;
commit;
